<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP7QsPhU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP7QsPhU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP7QsPhU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP7QsPhU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP7QsPhU\App_KernelDevDebugContainer([
    'container.build_hash' => 'P7QsPhU',
    'container.build_id' => 'bad5707f',
    'container.build_time' => 1695214117,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP7QsPhU');
